### ISSUE TITLE
[official] prettier-plugin-wxml roadmap

### ISSUE THREAD

**Issue by iChenLei** [wxmlfile/prettier-plugin-wxml#1]
- [ ] 1. Learn [prettier plugin doc](https://prettier.io/docs/en/plugins.html)
- [ ] 2. POC(proof of concept) development
- [ ] 3. Add unit test and finish beta development
- [ ] 4. Release `pretteir-plugin-wxml` to [npm](https://npmjs.org) and [npmmirror](https://npmmirror.com)
